<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CakeOS.Images.Interop</RootNamespace>
    <AssemblyName>CakeOS.Images.Interop</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\HUI\Platform\CakeOS.Platform.csproj" />
  </ItemGroup>
</Project>